<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3b8bfdef-a7c3-4488-b328-70f405e70597</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LynxGroup.Application\LynxGroup.Application.csproj" />
    <ProjectReference Include="..\LynxGroup.Domain\LynxGroup.Domain.csproj" />
    <ProjectReference Include="..\LynxGroup.Infrastructure\LynxGroup.Infrastructure.csproj" />
  </ItemGroup>

</Project>
